project:
  type: book
  output-dir: docs

book:
  title: "Da neofita di Python a campione"
  subtitle: "Corso di Python per tutti"
  author: 
    - name: "Antonio Montano"
      affiliations:
        - "4M4, Italy"
  date: "5/24/2024"
  page-navigation: true
  favicon: red-python-logo.png
  search: true
  repo-url: https://github.com/antomon/corso-python
  issue-url: https://github.com/antomon/corso-python/issues/new/choose
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  open-graph: true
  twitter-card: 
    creator: "@antomon"
    site: "@antomon"
  license: CC BY-NC-ND
  navbar:
    background: primary
    search: true
    left:
      - icon: "house-fill"
        href: index.qmd
      - text: "4M4"
        href: "https://4m4.it/"
  chapters:
    - index.qmd
    - part: prima-parte.qmd
      chapters: 
        - prima-parte-linguaggi-programmazione.qmd
        - prima-parte-paradigmi-programmazione.qmd
        - prima-parte-sintassi.qmd
        - prima-parte-variabili-funzioni.qmd
        - prima-parte-modello-dati.qmd
    - part: seconda-parte.qmd
      chapters: 
        - seconda-parte-python-introduzione.qmd
        - seconda-parte-python-installazione.qmd
        - seconda-parte-python-sintassi.qmd
        - seconda-parte-python-modello-dati.qmd
        - seconda-parte-esercizi.qmd
  appendices:
    - appendice-riferimenti.qmd
  page-footer:
    center: 
      - text: "Antonio Montano"
        href: antonio.qmd
      - text: "Come collaborare"
        href: come-collaborare.qmd
      - text: "4m4"
        href: "https://4m4.it"


copyright: 
  holder: Antonio Montano
  year: 2024

bibliography: references.bib

lang: it

format:
  html:
    theme: pulse
    code-line-numbers: true
    include-in-header:
      - text: |  
          <script src="https://cdn.jsdelivr.net/pyodide/v0.26.0/full/pyodide.js"></script>
  pdf:
    documentclass: scrbook
    geometry: "left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"
    cover-image: red-python.png
  epub:
    cover-image: red-python.png

comments:
  hypothesis: true


