project:
  type: book
  output-dir: docs

book:
  title: "Da neofita di Python a campione"
  author: "Antonio Montano"
  date: "5/24/2024"
  page-navigation: true
  search: true
  repo-url: https://github.com/antomon/corso-python
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  chapters:
    - index.qmd
    - part: fp.qmd
      chapters: 
        - fp-programming-languages.qmd
        - fp-programming-paradigms.qmd
        - fp-syntax-algorithm.qmd
    - part: sp.qmd
      chapters: 
        - sp-python-intro.qmd
        - sp-python-install.qmd
        - sp-python-syntax.qmd
        - sp-exercises.qmd
  appendices:
    - references.qmd

bibliography: references.bib

lang: it

format:
  html:
    theme: simplex
    include-in-header:
      - text: |  
          <script src="https://cdn.jsdelivr.net/pyodide/v0.26.0/full/pyodide.js"></script>
  pdf:
    documentclass: scrbook
    geometry: "left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"
    cover-image: red-python.png
  epub:
    cover-image: red-python.png

comments:
  hypothesis: true


