project:
  type: book
  output-dir: docs

book:
  title: "Da neofita di Python a campione"
  author: "Antonio Montano"
  date: "5/24/2024"
  page-navigation: true
  search: true
  repo-url: https://github.com/antomon/corso-python
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  chapters:
    - index.qmd
    - part: fp.qmd
      chapters: 
        - fp-programming-languages.qmd
        - fp-programming-paradigms.qmd
  appendices:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
    cover-image: red-python.webp
    cover-image-alt: |
      Pitone rosso 
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: red-python.webp

comments:
  hypothesis: true


